### ISSUE TITLE
Incense not detected 

### ISSUE THREAD

**Issue by Yako7u7** [kyan0045/CatchTwo#23] opened 2024-06-23 02:34 UTC
Recently PokeTwo was updated, in it some new functions were implemented to the incense, in the embed message there is a new section where it shows if: the incense is active, Spawn Remaining, Spawn interval and the time where the pokemon will finish appearing, the bot does not detect this Embed and does not execute the Hint or H command.
![Screenshot_2024-06-22-21-30-07-020_com discord-edit](https://github.com/kyan0045/CatchTwo/assets/102169740/597173e6-59c4-4768-b2c2-782943d238ae)

**Comment by kyan0045** [comment] 2024-06-26 17:08
Should work just fine, if you've got incenseMode enabled, it should just work, since the footer includes "Incense"
![image](https://github.com/kyan0045/CatchTwo/assets/84374752/53458e6f-8033-4c7d-9a8a-321d9fe93413)

**Comment by kyan0045** [comment] 2024-06-29 22:05
Gonna close it since you're not responding and it works fine when reproduced

**Closed by kyan0045** 2024-06-29 22:05 UTC
Labels: invalid, question
